// Generated by LiveScript 1.5.0
(function(){
  var swarm, signalhub, hsodium, split, sodium, hyperlog, Log, log, ref$, createAccount, toHex, Pub, Sub, hubs, AppShell, out$ = typeof exports != 'undefined' && exports || this;
  swarm = require('webrtc-swarm');
  signalhub = require('signalhub');
  hsodium = require('hyperlog-sodium');
  split = require('split2');
  sodium = require('chloride/browser');
  hyperlog = require('hyperlog');
  Log = require('./log-service');
  log = new Log;
  ref$ = require('./hyper-utils'), createAccount = ref$.createAccount, toHex = ref$.toHex;
  ref$ = require('./moon-classes'), Pub = ref$.Pub, Sub = ref$.Sub;
  hubs = ['http://localhost:1337'];
  out$.AppShell = AppShell = (function(){
    AppShell.displayName = 'AppShell';
    var prototype = AppShell.prototype, constructor = AppShell;
    AppShell.prototype.subs = [];
    AppShell.prototype.pubs = [];
    function AppShell(arg$){
      var hubs, publicKey, privateKey, debug;
      hubs = arg$.hubs, publicKey = arg$.publicKey, privateKey = arg$.privateKey, debug = arg$.debug;
      window.enableDebug = debug;
      this.log = log;
      log.info('init app shell with: ', arguments);
      this.key = createAccount();
      log.info('created new account: ', this.key);
      this.hubs = hubs;
    }
    AppShell.prototype.sub = function(arg$){
      var topic, secret, sub;
      topic = arg$.topic, secret = arg$.secret;
      sub = new Sub({
        topic: topic,
        secret: secret,
        hubs: this.hubs,
        db: this.db
      });
      this.subs.push(sub);
      return sub;
    };
    AppShell.prototype.pub = function(topic){
      var pub;
      pub = new Pub({
        topic: topic,
        hubs: this.hubs,
        db: this.db
      });
      this.pubs.push(pub);
      return pub;
    };
    AppShell.prototype.getWorkers = function(){
      return workers;
    };
    return AppShell;
  }());
}).call(this);
